name: habitat-gs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - cmake
  - numpy
  - scipy
  - pillow
  - matplotlib
  - pip:
      - open3d
      - laspy
      - lazrs

